### ISSUE TITLE
Looser validation for Braket AHS local simulator. 

### ISSUE THREAD

**Issue by weinbe58** [aws/amazon-braket-default-simulator-python#151]
**Describe the feature you'd like**
Relax validation on AHS local simulator. Currently the local simulator for AHS mode requries that all the driving fields have the same time-points for the input time series. This is not a restriction on QuEra's device which makes using the braket simulator to compare to Aquila a bit difficult. While merging the time points isn't really an issue for the simulator because there is no constraint on the the minimum time step in the time series, this is not the case on actual hardware. By merging the time points for each time series to fit the constraints of the simulator, you might create an invalid hardware task that violates the minimum time step constraint. 

**How would this feature be used? Please describe.**
Instead of requiring the time series to have the same point, a simple solution would be to simply transform the AHS program to the valid form for the simulator. Here is a function that would be able to do this:

```python
def merge_time_points(first_time_series: TimeSeries, second_time_series: TimeSeries) -> Tuple[TimeSeries, TimeSeries]:
    """Return new TimeSeries for the inputs by merging the time points from each series. 

    Args:
        first_time_series (TimeSeries): First time series to merge time points
        second_time_series (TimeSeries): Second time seroes to merge time points. 

    Returns:
        Tuple[TimeSeries, TimeSeries]: The new first and second time series with the merged time points respectively. 
        
    Note: This should be used with the Braket local simulator as it requires the time points for the driving fields to be the same. 
    """
    first_times = numpy.array(first_time_series.times(),dtype=object)
    second_times = numpy.array(second_time_series.times(),dtype=object)
    new_times = numpy.unique(numpy.hstack([first_times, second_times]))
    
    new_first_time_series = TimeSeries()
    new_second_time_series = TimeSeries()
    
    for time in new_times:
        new_first_time_series.put(time, get_time_series_value(first_time_series, time))
        new_second_time_series.put(time, get_time_series_value(second_time_series, time))  
        
    return new_first_time_series, new_second_time_series  
```

**Describe alternatives you've considered**
I have been using the above function to transform my AHS programs before submitting them to the local simulator.

**Comment by krneta** [comment]
Hi weinbe58,

Thank you very much for your suggestion! We recently added some new functions to TimeSeries, including stitch and concatenate in [this](https://github.com/aws/amazon-braket-sdk-python/pull/508/files#diff-ec09f3dd5ea2ddfec79a1afe92d1a4abb03b3adfb3506e80969e2260af593698R134) change. Would one of those cover your use case?

**Comment by weinbe58** [comment]
@krneta Yes this would however, I think it would be better if this transformation is performed by the simulator automatically as opposed to forcing the user to do it.  

The most common use case for the simulator is for benchmarking quantum hardware. When comparing the simulator to quantum hardware, forcing the user to transform their AHS program to run it on the simulator leads to a higher probability of errors.

**Comment by maolinml** [comment]
Hi Phillip, a few things
1. Regarding the comment "Currently the local simulator for AHS mode requries that all the driving fields have the same time-points for the input time series.", this is actually not the case. The local simulator can run tasks with driving fields with different time points, as long as their durations are the same. Did you see different behaviors?
2. You may have this impression from the util function `drive = get_drive(time_points, amplitude_values, detuning_values, phase_values)` in some of the examples (which is now part of BDK, see [here](https://github.com/aws/amazon-braket-sdk-python/blob/c5cf3cbf1026dcdf54018539ee5ae86ebf65f5fc/src/braket/ahs/driving_field.py#L143)), but it is just used for specifying a simple driving field with the same time points for all time series. More general driving fields are acceptable, but not through that util function.
3. With that said, by design, anything that can run on the hardware can be run on the local simulator, but not the other way around. 
4. With that said, regarding the proposed function `merge_time_points`, it is almost the same as the current implementation for simulating the driving field with the local simulator. In particular, I assume `get_time_series_value` is an (linear) interpolation function to get the value of a time series at certain time, this is precisely what is done [here](https://github.com/weinbe58/amazon-braket-default-simulator-python/blob/da005c954f4411f5ec9e787a4bf2a680d38cb86c/src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py#L263). The only difference is that we treat the phase of the driving field as piecewise constant function. 

Please let me know if these make sense.

**Comment by maolinml** [comment]
Yeah, the reason is here 
```
phase = TimeSeries()
phase.put(0.0,0.0)
phase.put(0.0,3.0e-6)
```
It gives a time series of duration zero (both time points are at zero), and hence the error.

**Comment by weinbe58** [comment]
OMG that's really dumb 😂 Thanks for humoring me!

**Comment by maolinml** [comment]
Believe it or not, I have done worse before 😂. Also I think the error message is a bit misleading, we will try to fix it.
